### ISSUE TITLE
_GeoIP_inet_pton() on Windows

### ISSUE THREAD

**Issue by White-Tiger** [maxmind/geoip-api-c#86] opened 2017-04-12 11:16 UTC
Is it possible that `_GeoIP_inet_pton(int af, const char *src, void *dst)` actually never worked?
[inet_pton()](http://man7.org/linux/man-pages/man3/inet_pton.3.html)'s `dst` parameter is meant to be `in_addr` or `in6_addr` depending on `af`.

That's also how GeoIP uses it... _(though the `.s6_addr[0]` part is quite useless and confusing)_
```c
geoipv6_t
_GeoIP_addr_to_num_v6(const char *addr)
{
    geoipv6_t ipnum;
    if (1 == _GeoIP_inet_pton(AF_INET6, addr, &ipnum.s6_addr[0] ) ) {
        return ipnum;
    }
    return IPV6_NULL;
}
````
yet the implementation looks like this:
```c
static int _GeoIP_inet_pton(int af, const char *src, void *dst)
{
    struct addrinfo hints, *res, *ressave;

    memset(&hints, 0, sizeof(struct addrinfo));
    hints.ai_family = af;

    if (getaddrinfo(src, NULL, &hints, &res) != 0) {
        return -1;
    }

    ressave = res;

    while (res) {
        memcpy(dst, res->ai_addr, res->ai_addrlen);
        res = res->ai_next;
    }

    freeaddrinfo(ressave);
    return 0;
}
```

and `res->ai_addr` is a full-blown socket address returned by [getaddrinfo()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms737530(v=vs.85).aspx) , not just the network address.

**So a working implementation could look like this**
_(also fixed the return value of `_GeoIP_inet_pton()` and corrected the address return  behavior)_
```c
static int _GeoIP_inet_pton(int af, const char *src, void *dst)
{
    struct addrinfo hints, *res;

    memset(&hints, 0, sizeof(struct addrinfo));
    hints.ai_family = af;

    if (getaddrinfo(src, NULL, &hints, &res) != 0) {
        return 0;
    }

    if(af == AF_INET)
        memcpy(dst, &((struct sockaddr_in*)res->ai_addr)->sin_addr, sizeof(struct in_addr));
    else
        memcpy(dst, &((struct sockaddr_in6*)res->ai_addr)->sin6_addr, sizeof(struct in6_addr));

    freeaddrinfo(res);
    return 1;
}
```

**P.S.** one could also replace the "custom" `GeoIP_addr_to_num()` implementation so that IPv6 and IPv4 are unified and to detect bugs in `inet_pton()` earlier...
```c
unsigned long
GeoIP_addr_to_num(const char *addr)
{
    unsigned long ipnum;
    if (1 == _GeoIP_inet_pton(AF_INET, addr, &ipnum ) ) {
        return htonl(ipnum);
    }
    return 0;
}
```

**Comment by oschwald** [comment] 2017-04-12 14:02
It is certainly possible that the function doesn't work as intended on Windows. Would you mind making this into a PR for review?

**Comment by White-Tiger** [comment] 2017-04-12 15:20
I would mind a PR yes... because that'll mean about 30 minutes of extra work which is quite unnecessary considering that I'll just reuse the same information already present here... _(though it took me longer to find, fix and post the bug here^^)_

Also, I'm not quite sure about the PR concept that Github uses... as to when I'm allowed to delete my fork, if I have to use a different branch et cetera. I don't like zombie repositories on my account.

**Comment by oschwald** [comment] 2017-04-12 16:48
Without a PR, it is harder for us to review the changes and we don't have the benefit of our CI running on it. I'll make an internal ticket to look into this, but our current focus is on the `libmaxminddb` API and the related GeoIP2 APIs.

**Comment by oschwald** [comment] 2020-06-17 18:48
Given that the legacy databases have an [EOL date set](https://blog.maxmind.com/2020/06/01/retirement-of-geoip-legacy-downloadable-databases-in-may-2022/) and there have been no additional reports of the issue, it seems unlikely that we would address this before the EOL. As such, I am going to go ahead and close this.

**Closed by oschwald** 2020-06-17 18:48 UTC
